app/unfollow/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import SubmitField
from wtforms.validators import DataRequired
from wtforms.validators import Optional
from wtforms.validators import ValidationError

from app.models import Department
from app.models import Shop


class EditForm(FlaskForm):
    name = StringField('Как Вас зовут?', validators=[DataRequired(message="Это поле обязательно для заполнения")])
    surname = StringField('Ваша фамилия', validators=[DataRequired(message="Это поле обязательно для заполнения")])
    about_me = StringField('Расскажите о себе', validators=[Optional()])
    position = StringField('Ваша должность', validators=[DataRequired(message="Это поле обязательно для заполнения")])
    submit = SubmitField("Подтвердить")


class ChoiceForm(FlaskForm):
    shop = StringField("Название магазина, либо его код",
                       validators=[DataRequired(message="Это поле обязательно для заполнения")])
    department = StringField("Название отдела",
                             validators=[DataRequired(message="Это поле обязательно для заполнения")])
    submit = SubmitField("Подтвердить")

    def validate_shop(self, shop_name):
        shop = Shop.query.filter(Shop.name == shop_name.data or Shop.shop_code == shop_name.data).first()
        if not shop:
            raise ValidationError("Такой магазин отсутствует")  # TODO показать ближайшие к введенному значению

    def validate_department(self, department_name):
        department = Department.query.filter_by(name=department_name.data).first()
        if not department:
            raise ValidationError("Такой отдел отсутствует")


class CreateShopForm(FlaskForm):
    name = StringField("Название магазина",
                       validators=[DataRequired(message="Это поле обязательно для заполнения")])
    shop_code = StringField("Код магазина",
                            validators=[DataRequired(message="Это поле обязательно для заполнения")])
    submit = SubmitField("Создать")

app/unfollow/__init__.py
from flask import Blueprint

bp = Blueprint('unfollow', __name__)

from app.unfollow import routes

app/unfollow/routes.py
from flask import flash
from flask import redirect
from flask import render_template
from flask import url_for
from flask_login import current_user
from flask_login import login_required

from app import db
from app.models import Department
from app.models import Permission
from app.models import Request
from app.models import Shop
from app.unfollow import bp
from app.unfollow.forms import ChoiceForm
from app.unfollow.forms import CreateShopForm
from app.unfollow.forms import EditForm


@bp.route('/edit', methods=['GET', 'POST'])
@login_required
def first_edit_profile():
    if current_user.can(Permission.WRITE):
        flash("Вы уже состоите в магазине")
        return redirect(url_for('main.index'))
    form = EditForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.surname = form.surname.data
        current_user.about_me = form.about_me.data
        current_user.position = form.position.data
        db.session.add(current_user)
        db.session.commit()
        return redirect(url_for('unfollow.first_choice'))
    form.name.data = current_user.name
    form.surname.data = current_user.surname
    form.about_me.data = current_user.about_me
    form.position.data = current_user.position
    return render_template('unfollow/edit.html', form=form, name=current_user.username)


@bp.route('/choice', methods=['GET', 'POST'])
@login_required
def first_choice():
    if current_user.can(Permission.WRITE):
        flash("Вы уже состоите в магазине")
        return redirect(url_for('main.index'))
    if not current_user.name or not current_user.surname or not current_user.position:
        return redirect(url_for('unfollow.first_edit_profile'))
    form = ChoiceForm()
    if form.validate_on_submit():
        shop = Shop.query.filter(Shop.name == form.shop.data or Shop.shop_code == form.shop.data).first()
        department = Department.query.filter_by(name=form.department.data).first()
        r = Request(user=current_user, shop=shop, department=department)
        db.session.add(r)
        db.session.commit()
        flash("Ваша заявка сформирована")
        return redirect(url_for('unfollow.wait', shop=form.shop.data))  # TODO create request
    return render_template('unfollow/choice.html', form=form, name=current_user.name)


@bp.route('/wait/<shop>/<department>')
@login_required
def wait(shop, department):
    if current_user.can(Permission.WRITE):
        flash("Вы уже состоите в магазине")
        return redirect(url_for('main.index'))
    if not current_user.name or not current_user.surname or not current_user.position:
        flash("Не хватает ваших данных")
        return redirect(url_for('unfollow.first_edit_profile'))
    shop_instance = Shop.query.filter(Shop.name == shop or Shop.shop_code == shop).first()
    department_instance = Department.query.filter_by(name=department).first()
    request = Request.query.filter_by(user=current_user,
                                      shop=shop_instance,
                                      department=department_instance).first()
    if not request:
        flash("Заявка не сформирована")
        return redirect(url_for('unfollow.first_choice'))
    return render_template('unfollow/wait.html')


@bp.route('/create', methods=['POST', 'GET'])
@login_required
def create_shop():
    if current_user.can(Permission.WRITE):
        flash("Вы уже состоите в магазине")
        return redirect(url_for('main.index'))
    if not current_user.name or not current_user.surname or not current_user.position:
        flash("Не хватает ваших данных")
        return redirect(url_for('unfollow.first_edit_profile'))
    form = CreateShopForm()
    if form.validate_on_submit():
        shop_name = form.name.data
        shop_code = form.shop_code.data
        Shop.create_shop(current_user, shop_name, shop_code)
        db.session.commit()
        flash("Магазин создан")
        return redirect(url_for('main.index'))  # TODO на страницу магазина
    return render_template('unfollow/create.html', form=form)

app/templates/unfollow/choice.html
{% extends "base.html" %}

{% block content %}
    <p>Выберите магазин</p>
     <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.shop.label }}<br>
            {{ form.shop(size=32) }}<br>
            {% for error in form.shop.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
         <p>
            {{ form.department.label }}<br>
            {{ form.department(size=32) }}<br>
            {% for error in form.department.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
    <p>Хотите зарегистрировать свой магазин?
        <a href="{{ url_for('unfollow.create_shop') }}"> Перейдите по ссылке</a>
    </p>
{% endblock %}

app/templates/unfollow/create.html
{% extends "base.html" %}

{% block content %}
    <p>Создание магазина</p>
    <form action="" method="post">
                {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}<br>
            {{ form.name(size=32) }}<br>
            {% for error in form.name.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.shop_code.label }}<br>
            {{ form.shop_code(size=64) }}<br>
            {% for error in form.shop_code.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/unfollow/edit.html
{% extends "base.html" %}

{% block content %}
    <p>Сбор информации</p>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}<br>
            {{ form.name(size=32) }}<br>
            {% for error in form.name.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.surname.label }}<br>
            {{ form.surname(size=64) }}<br>
            {% for error in form.surname.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.about_me.label }}<br>
            {{ form.about_me(size=32) }}<br>
            {% for error in form.about_me.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.position.label }}<br>
            {{ form.position(size=32) }}<br>
            {% for error in form.position.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/unfollow/wait.html
{% extends "base.html" %}

{% block content %}
    <p>Заявка на вступление в братство сформирована, ожидайте её подтверждения...</p>
{% endblock %}